---
title: "Day 3: Historical-Strategic Rivalries"
output: html_notebook
---

```{r}
library(tidyverse)
library(gganimate)
library(ggraph)
library(igraph)
library(tidygraph)
```

```{r}
# Source data :https://gist.github.com/svmiller/63dace4aa5a00eddce307d964c7bac23#file-strategic_rivalries-csv
strategic_rivalries <- read_csv('data/strategic_rivalries.csv')
```

```{r}
ggraph_df <- strategic_rivalries %>%
  mutate(sidea = if_else(sidea == 'Great Britain','Britain',sidea),
         sideb = if_else(sidea == 'Great Britain','Britain',sideb)) %>% 
  rename(from = sidea, to = sideb) %>%

  mutate(styear  = as.integer(styear),
         endyear = as.integer(endyear), ) %>%
  add_count(from) %>%
  #filter(n > 1) %>%
  as_tbl_graph(directed  = FALSE) %>%
  activate(nodes) %>%
  mutate(
    community = as.factor(group_louvain())
  )
```
```{r}
strategic_rivalries %>%
  mutate(sidea = if_else(sidea == 'Great Britain','Britain',sidea),
         sideb = if_else(sidea == 'Great Britain','Britain',sideb)) %>% 
  count(sidea,sort = TRUE)
```


```{r}
p <- ggraph_df %>% 
  ggraph(layout = 'kk') +
  geom_edge_link(edge_colour = '#991814', edge_width = 1, edge_alpha = 1) +
    geom_node_text(aes(label = name,color =community ),size = 5,check_overlap = TRUE) +
  #geom_node_point(aes(,color =community )) +
  #scale_color_tableau() +
  #scale_edge_color_manual(values = c('#118ab2', '#ef476f','#2a9d8f','#e76f51')) +
  theme_graph()+
  theme(legend.position = 'none')+
  labs(title = 'Strategic Rivalries', subtitle = 'Year {frame_time}') +
  transition_events( start= styear,end = endyear, enter_length = 1L, exit_length = 3L  ) +
  enter_fade() + 
  exit_fade()

#p
animate(p, 100, 2,height = 1100, width = 1100)

```

```{r fig.height=20,fig.width=20}
ggraph_df %>% 
  ggraph(layout = 'kk') +
  geom_edge_link(edge_colour = '#991814', edge_width = 1, edge_alpha = 1) +
    geom_node_text(aes(label = name,color =community ),size = 5,check_overlap = TRUE) +
  #geom_node_point(aes(,color =community )) +
  #scale_color_tableau() +
  #scale_edge_color_manual(values = c('#118ab2', '#ef476f','#2a9d8f','#e76f51')) +
  theme_graph()+
  theme(legend.position = 'none')+
  labs(title = 'Strategic Rivalries', subtitle = 'Year {frame_time}')
```

