---
title: "Day 4: Magical"
output: html_notebook
---

```{r}
install.packages("harrypotter") #https://github.com/aljrico/harrypotter

library(tidyverse)
library(spotifyr)
library(harrypotter)
library(hrbrthemes)
```

```{r}
access_token <- get_spotify_access_token(client_id = "your_tokens",
                                         client_secret = 'your_tokens')

```

```{r}
track <- get_track_audio_analysis('1n8NKQRg8LVHy7oUhUgbFF') #Hedwig's theme
```

```{r}
segments <- track$segments %>%
  mutate(xend = start + duration) 
sections <- track$sections%>%
  mutate(xend = start + duration)
```

```{r fig.height=10,fig.width=10}
p <- ggplot() +
    geom_segment(
      data = segments,
      aes( x = start,
           y = loudness_start,
           xend = xend ,
           yend = loudness_end,
           color = confidence
      ),alpha  = 0.3,size = 1.1,
      
    ) +
    geom_segment(
      data = sections,
      aes( x = start,
           y = loudness,
           xend = xend ,
           yend = tempo,
      ),alpha  = 0.3,size = 1.1,color ="#803525"
      
    ) +
      geom_segment(
      data = sections,
      aes( x = start,
           y = tempo,
           xend = xend ,
           yend = tempo,
      ),alpha  = 0.3,size = 1.1,color ="#5f1416"
      
    ) +
  scale_color_gradientn(colours = hp(n = 128, house = "Gryffindor")) +
  labs( title = 'Hedwig’s Theme',
        caption = 'Data: Spotify\n Visualization: mcnakhaee') +
  coord_polar() +
  theme_void() +
  theme(plot.background = element_rect(fill = 'grey95', color = NA),
        plot.title = element_text(face = 'bold',
                                  color = '#5f1416',
                                  size = 24,hjust=0.5,
                                  margin = margin(t = 40),
                                    family = "Montserrat"),
        plot.caption = element_text(size = 10,
                                    margin = margin(b = 20,r = 10),
                                    family = "Montserrat"),
        legend.position = 'none')
```

```{r}
ggsave(filename = 'Day4-Magic.png',path = here::here('plots'),plot = p ,
                      dpi = 300, width = 10, height =10)
```



